#pragma once

namespace Renderer
{
	enum RenderType
	{
		RENDER_QUADSPRITE = 0x0,
		RENDER_GROUND_ALIGNED_SPRITE = 0x1,
		RENDER_BILLBOARD_SPRITE = 0x2,
		RENDER_2D_SPRITE = 0x3,
		RENDER_TRIANGLE_SPRITE = 0x4,
		RENDER_QUAD_SPRITE_FROM_VERTS = 0x5,
		RENDER_TYPE6 = 0x6,
		RENDER_TYPE7 = 0x7,
		RENDER_TYPE8 = 0x8,
		RENDER_TYPE9 = 0x9,
		RENDER_TYPE10 = 0xA,
	};
}
